name: "Pull Request linkcheck"
on: 
- pull_request

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Install prerequisites
      run: | 
        sudo apt-get --allow-releaseinfo-change update -y && sudo apt-get install -y tox
    - name: Building docs
      run: |
        echo "---------------------------------------------------------------------------------------"
        echo "---------------------------------- Checking links -------------------------------------"
        echo "---------------------------------------------------------------------------------------"
        tox -e justlinks
        echo "Linkcheck was successfull! "


        
